### ISSUE TITLE
大佬，请问如下报错应如何处理，谢谢

### ISSUE THREAD

**Issue by 19819068211** [SocialSisterYi/xuexiaoyi-to-xuexitong-tampermonkey-proxy#10]
大佬，请问如下报错应如何处理，谢谢
![image](https://user-images.githubusercontent.com/66981884/196883861-dc411560-ed91-44c4-affc-39222241d363.png)
C:\Users\jl\Downloads\xuexiaoyi-to-xuexitong-tampermonkey-proxy-main>python app.py
Traceback (most recent call last):
  File "app.py", line 11, in <module>
    import cxsecret_font
  File "C:\Users\jl\Downloads\xuexiaoyi-to-xuexitong-tampermonkey-proxy-main\cxsecret_font.py", line 19, in <module>
    class FontHashDAO:
  File "C:\Users\jl\Downloads\xuexiaoyi-to-xuexitong-tampermonkey-proxy-main\cxsecret_font.py", line 21, in FontHashDAO
    char_map: dict[str, str] # unicode -> hsah
TypeError: 'type' object is not subscriptable

**Comment by SocialSisterYi** [comment]
已经修复，变量名和内置函数冲突了

**Comment by 19819068211** [comment]
![image](https://user-images.githubusercontent.com/66981884/196897393-81768950-de96-4361-909d-60f5d0ba99ee.png)
使用了最新的可还是这样报错

**Comment by 19819068211** [comment]
python版本3.8，应该满足3.6以上了，请问哪个版本的python可以支持，谢谢
![image](https://user-images.githubusercontent.com/66981884/196898883-78b3da91-fc93-4ae0-a6e9-4437745909db.png)

**Comment by SocialSisterYi** [comment]
> python版本3.8，应该满足3.6以上了，请问哪个版本的python可以支持，谢谢 ![image](https://user-images.githubusercontent.com/66981884/196898883-78b3da91-fc93-4ae0-a6e9-4437745909db.png)

我理解了，这里用了 Py 3.9 的一个类型注解特性 [GenericAlias 类型](https://docs.python.org/zh-cn/3/library/stdtypes.html#types-genericalias) 所以低版本会报错，把注解中的`dict`改为`typing.Dict`就解决了

**Comment by 19819068211** [comment]
![image](https://user-images.githubusercontent.com/66981884/196912609-4e98d668-7095-4ecc-9ce5-3828f9dea0f7.png)
不好意思再次打扰，又有报错

**Comment by 19819068211** [comment]
![image](https://user-images.githubusercontent.com/66981884/196915462-d91f85a3-537c-41c8-9d6b-1c700e1891b6.png)
items: list[dict]
TypeError: 'type' object is not subscriptable
