### ISSUE TITLE
请问运行报错，缺少cache.json应该怎么办

### ISSUE THREAD

**Issue by 19819068211** [SocialSisterYi/xuexiaoyi-to-xuexitong-tampermonkey-proxy#4]
请问运行报错，缺少cache.json应该怎么办
FileNotFoundError: [Errno 2] No such file or directory: 'cache.json
![屏幕截图(90)](https://user-images.githubusercontent.com/66981884/164416191-5ce28f87-4d27-4ebd-972f-dd6688df6248.png)
'

**Comment by SocialSisterYi** [comment]
是我的json缓存机制没有做好，稍等就修复

**Comment by SocialSisterYi** [comment]
#3
