### ISSUE TITLE
大佬，学小易能搜到的题，脚本不能返回答案了

### ISSUE THREAD

**Issue by 19819068211** [SocialSisterYi/xuexiaoyi-to-xuexitong-tampermonkey-proxy#5]
大佬，学小易能搜到的题，脚本不能返回答案了，网页返回：{"code":-1,"data":"\ud83d\ude4c\u6ca1\u6709\u4eba \ud83d\udc50\u6bd4\u6211 \u261d\ufe0f\u66f4\u61c2 \ud83d\udc4c\u505a\u9898","messsage":"list index (0) out of range"}

**Comment by SocialSisterYi** [comment]
#1
